config/routes.rb
Rails.application.routes.draw do
  get "/score/test/:id" => "tests#score" ,as: :score
  get "/test/:id/result" => "tests#result", as: :result
  
  resources :answers
  resources :tests 
  resources :test_questions
  get 'home/index'
  root to: "home#index"

 get "users/results" => "admin/tests#user", as: :users
 get "user/:id/result" => "admin/tests#user_result", as: :user_result
  devise_for :users
  
  get "test/:id" => "tests#paper", as: :paper
  get "start_test/:id" => "tests#start_test", as: :start_test
  post "test/:id" => "tests#submit", as: :submit
  namespace :admin do
    resources :tests
    resources :questions
  end
  get "/*args"=>"tests#undef"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :test
  has_many :answer_options , dependent: :destroy
  has_many :options , through: :answer_options
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :option
  belongs_to :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
  has_many :answer_options , dependent: :destroy
  validates :choice , presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true
  has_many :test_questions , dependent: :destroy
  has_many :tests , through: :test_questions
  has_many :answers , dependent: :destroy
  validates :question, :question_type, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
 
end

app/models/test.rb
class Test < ApplicationRecord
	has_many :test_questions, dependent: :destroy
	has_many :questions, through: :test_questions 
	has_many :answers , dependent: :destroy
	has_many :results , dependent: :destroy
	validates :name , :duration, :questions, presence: true
end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  belongs_to :test
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:timeoutable
  has_many :answers , dependent: :destroy
  has_many :results , dependent: :destroy
  validates :email, :password, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :require_admin
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to admin_questions_path, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to admin_questions_path, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to admin_questions_path, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
        @question = Question.find(params[:id])
    end

      # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
        params.require(:question).permit(:question, :question_type , options_attributes: [:id, :choice, :is_correct, :_destroy])
    end
    def require_admin
        unless current_user && User.find(current_user.id).admin
            redirect_to root_path, notice:"You are not admin!"
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
 before_action :set_test, only: [:start_test, :paper, :submit, :result]
  
  def paper
    @questions = @test.questions.page(params[:page]).per_page(1)
    @answers = @questions.first.answers.where(user_id: current_user.id, test_id: @test)
    @answer = @questions.first.answers.new
  end

  def start_test
 
  end

  def submit

    @test = Test.find(params[:id])
    @user = current_user.id
    Answer.where(user_id:current_user.id,question_id:answer_paper_params[:question_id],test_id:params[:id]).destroy_all
    @answer = @test.answers.new(answer_paper_params)
    @answer.user_id = @user
    @answer.save
    @ans_maq = @answer.options.map(& :is_correct)
      if @ans_maq.size == 1   
        if @ans_maq.include?(false)       
         @answer.score = 0
        else
         @answer.score = 1 
        end
     else
      if @ans_maq.include?(false)
         @answer.score = 0
      else
         @answer.score = 1
      end
    end
    @answer.save
  end
   
  def score
    @test=Test.find(params[:id])
    @score = Answer.where(user_id:current_user.id, test_id:@test)
    @result=Result.new
    render "score"
  end

  def result
   @result=Result.where(user_id: current_user.id)
  end

  def undef
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    def answer_paper_params
      params.require(:answer).permit(:score, :user_id, :test_id, :question_id, :option_ids=>[])
    end

    def test_params
      params.require(:test).permit(:question_id, :name, :duration, question_ids: [])
    end
end

app/helpers/answer_helper.rb
module AnswerHelper
	def is_check(answers, option_id)
        return false if answers.blank?
        	answers.each do |answer|
           		answer.options.each do |check|
           		return check.id == option_id
       		end
        end
    end	
    
end

app/helpers/answer_options_helper.rb
module AnswerOptionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 def paginate(collection, params= {})
    will_paginate collection, params.merge(:renderer => RemoteLinkPaginationHelper::LinkRenderer)
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
	
end

app/helpers/remote_link_pagination_helper.rb
module RemoteLinkPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    def link(text, target, attributes = {})
      attributes['data-remote'] = true
      super
    end
  end
end

app/helpers/test_questions_helper.rb
module TestQuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/questions/_form.html.erb
<%= nested_form_for [:admin,@question], :html => { :class => "form-horizontal question" } do |f| %>

  <% if @question.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :question, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :question, :class => 'form-control' %>
    </div>
    <%=f.error_span(:question) %>
  </div>
  <div class="form-group">
    <%= f.label :question_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :question_type, ['MCQ', 'MAQ','Fill in the blanks','True/False'],{},{:class => 'question_type form-control'} %>
    </div>
    <%=f.error_span(:question) %>
  </div>
  <div class="form-group">
    <%= f.label :options, :class => 'control-label col-lg-2' %>
  </div>
    <%= f.fields_for :options do |option_form| %>
      <%%>
      <%= option_form.text_field :choice %>
      <%= option_form.check_box :is_correct, :class=> "check_box" %>
      <%= option_form.link_to_remove "Remove this option" %>
    <% end %>
        <p><%= f.link_to_add "Add a option", :options %></p>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_questions_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, admin_question_path(question) %></td>
        <td><%= question.question %></td>
        <td><%=l question.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      admin_question_path(question), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_question_path(question), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_question_path(question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_question_path,
            :class => 'btn btn-primary' %>

app/views/admin/questions/new.html.erb
<%- model_class = Question -%>
	<div class="page-header">
	  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
	</div>
<%= render :partial => 'form' %>

app/views/admin/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:question) %>:</strong></dt>
  <dd><%= @question.question %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:question_type) %>:</strong></dt>
  <dd><%= @question.question_type %></dd>
</dl>
<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_questions_path, :class => 'btn btn-primary btn-xs div'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_question_path(@question), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              edit_admin_question_path(@question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>