config/routes.rb
Rails.application.routes.draw do
  get "/score/test/:id" => "tests#score" ,as: :score
  get "/test/:id/result" => "tests#result", as: :result
  
  resources :answers
  resources :tests 
  resources :test_questions
  get 'home/index'
  root to: "home#index"

 get "users/results" => "admin/tests#user", as: :users
 get "user/:id/result" => "admin/tests#user_result", as: :user_result
  devise_for :users
  
  get "test/:id" => "tests#paper", as: :paper
  get "start_test/:id" => "tests#start_test", as: :start_test
  post "test/:id" => "tests#submit", as: :submit
  namespace :admin do
    resources :tests
    resources :questions
  end
  get "/*args"=>"tests#undef"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :test
  has_many :answer_options , dependent: :destroy
  has_many :options , through: :answer_options
end

app/models/answer_option.rb
class AnswerOption < ApplicationRecord
  belongs_to :option
  belongs_to :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
  has_many :answer_options , dependent: :destroy
  validates :choice , presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true
  has_many :test_questions , dependent: :destroy
  has_many :tests , through: :test_questions
  has_many :answers , dependent: :destroy
  validates :question, :question_type, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :test
 
end

app/models/test.rb
class Test < ApplicationRecord
	has_many :test_questions, dependent: :destroy
	has_many :questions, through: :test_questions 
	has_many :answers , dependent: :destroy
	has_many :results , dependent: :destroy
	validates :name , :duration, :questions, presence: true
end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  belongs_to :test
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:timeoutable
  has_many :answers , dependent: :destroy
  has_many :results , dependent: :destroy
  validates :email, :password, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
 before_action :set_test, only: [:start_test, :paper, :submit, :result]
  
  def paper
    @questions = @test.questions.page(params[:page]).per_page(1)
    @answers = @questions.first.answers.where(user_id: current_user.id, test_id: @test)
    @answer = @questions.first.answers.new
  end

  def start_test
 
  end

  def submit

    @test = Test.find(params[:id])
    @user = current_user.id
    Answer.where(user_id:current_user.id,question_id:answer_paper_params[:question_id],test_id:params[:id]).destroy_all
    @answer = @test.answers.new(answer_paper_params)
    @answer.user_id = @user
    @answer.save
    @ans_maq = @answer.options.map(& :is_correct)
      if @ans_maq.size == 1   
        if @ans_maq.include?(false)       
         @answer.score = 0
        else
         @answer.score = 1 
        end
     else
      if @ans_maq.include?(false)
         @answer.score = 0
      else
         @answer.score = 1
      end
    end
    @answer.save
  end
   
  def score
    @test=Test.find(params[:id])
    @score = Answer.where(user_id:current_user.id, test_id:@test)
    @result=Result.new
    render "score"
  end

  def result
   @result=Result.where(user_id: current_user.id)
  end

  def undef
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    def answer_paper_params
      params.require(:answer).permit(:score, :user_id, :test_id, :question_id, :option_ids=>[])
    end

    def test_params
      params.require(:test).permit(:question_id, :name, :duration, question_ids: [])
    end
end

app/helpers/answer_helper.rb
module AnswerHelper
	def is_check(answers, option_id)
        return false if answers.blank?
        	answers.each do |answer|
           		answer.options.each do |check|
           		return check.id == option_id
       		end
        end
    end	
    
end

app/helpers/answer_options_helper.rb
module AnswerOptionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
 def paginate(collection, params= {})
    will_paginate collection, params.merge(:renderer => RemoteLinkPaginationHelper::LinkRenderer)
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
	
end

app/helpers/test_questions_helper.rb
module TestQuestionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Onlinetest" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%  if action_name != "paper" %>
      <%= nav_bar static: :top, brand: "OnlineTest", responsive: true do %>
        <%= menu_group do %>
          <%= menu_item "Home", root_path %>
          <%= menu_divider %>
          <%= menu_item "Test",admin_tests_path %>
          <% if current_user && current_user.admin? %>
            <%= menu_item "Questions", admin_questions_path %>  
            <%= menu_item "Users",users_path %>
          <% end %>
        <% end %>
        <%= menu_group pull: :right do %>
          <% if current_user %>
            <%= menu_item "Log Out",destroy_user_session_path,
              method: :delete %>
            <%= menu_item current_user.email %>
          <% else %>
            <%= menu_item "Sign Up", new_registration_path(resource_name) %>
            <%= menu_item "Sign In",new_user_session_path%>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div> 
  </body>
  <footer>
    <div class="copyrite">
      <p>&copy; Company 2019 </p>
    </div>
  </footer>
</html>